export const GET_DOCTOR = "GET_DOCTOR";
export const GET_DOCTOR_SUCCESS = "GET_DOCTOR_SUCCESS";
export const GET_DOCTOR_FAIL = "GET_DOCTOR_FAIL";

export const ADD_NEW_DOCTOR = "ADD_NEW_DOCTOR";
export const ADD_NEW_DOCTOR_SUCCESS = "ADD_NEW_DOCTOR_SUCCESS";
export const ADD_NEW_DOCTOR_FAIL = "ADD_NEW_DOCTOR_FAIL";

export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const UPDATE_DOCTOR_SUCCESS = "UPDATE_DOCTOR_SUCCESS";
export const UPDATE_DOCTOR_FAIL = "UPDATE_DOCTOR_FAIL";

export const DELETE_DOCTOR = "DELETE_DOCTOR";
export const DELETE_DOCTOR_SUCCESS = "DELETE_DOCTOR_SUCCESS";
export const DELETE_DOCTOR_FAIL = "DELETE_DOCTOR_FAIL";

export const RESET_DOCTOR_STATE = "RESET_DOCTOR_STATE";
