// GET Reports
export const GET_REPORTS = "GET_REPORTS";
export const GET_REPORTS_SUCCESS = "GET_REPORTS_SUCCESS";
export const GET_REPORTS_FAIL = "GET_REPORTS_FAIL";

// ADD Report
export const ADD_NEW_REPORT = "ADD_NEW_REPORT";
export const ADD_NEW_REPORT_SUCCESS = "ADD_NEW_REPORT_SUCCESS";
export const ADD_NEW_REPORT_FAIL = "ADD_NEW_REPORT_FAIL";

// UPDATE Report
export const UPDATE_REPORT = "UPDATE_REPORT";
export const UPDATE_REPORT_SUCCESS = "UPDATE_REPORT_SUCCESS";
export const UPDATE_REPORT_FAIL = "UPDATE_REPORT_FAIL";

// DELETE Report
export const DELETE_REPORT = "DELETE_REPORT";
export const DELETE_REPORT_SUCCESS = "DELETE_REPORT_SUCCESS";
export const DELETE_REPORT_FAIL = "DELETE_REPORT_FAIL";

// RESET Report State
export const RESET_REPORT_STATE = "RESET_REPORT_STATE";
