export const GET_PATHOLOGY = "GET_PATHOLOGY";
export const GET_PATHOLOGY_SUCCESS = "GET_PATHOLOGY_SUCCESS";
export const GET_PATHOLOGY_FAIL = "GET_PATHOLOGY_FAIL";

export const ADD_NEW_PATHOLOGY = "ADD_NEW_PATHOLOGY";
export const ADD_NEW_PATHOLOGY_SUCCESS = "ADD_NEW_PATHOLOGY_SUCCESS";
export const ADD_NEW_PATHOLOGY_FAIL = "ADD_NEW_PATHOLOGY_FAIL";

export const UPDATE_PATHOLOGY = "UPDATE_PATHOLOGY";
export const UPDATE_PATHOLOGY_SUCCESS = "UPDATE_PATHOLOGY_SUCCESS";
export const UPDATE_PATHOLOGY_FAIL = "UPDATE_PATHOLOGY_FAIL";

export const DELETE_PATHOLOGY = "DELETE_PATHOLOGY";
export const DELETE_PATHOLOGY_SUCCESS = "DELETE_PATHOLOGY_SUCCESS";
export const DELETE_PATHOLOGY_FAIL = "DELETE_PATHOLOGY_FAIL";

export const RESET_PATHOLOGY_STATE = "RESET_PATHOLOGY_STATE";
